export const GET_CATEGORIES_ONLY_NAME_REQUEST = 'GET_CATEGORIES_ONLY_NAME_REQUEST'
export const GET_CATEGORIES_ONLY_NAME_SUCCESS = 'GET_CATEGORIES_ONLY_NAME_SUCCESS'
export const GET_CATEGORIES_ONLY_NAME_FAIL = 'GET_CATEGORIES_ONLY_NAME_FAIL'

export const GET_CATEGORY_DETAILS_REQUEST = 'GET_CATEGORY_DETAILS_REQUEST'
export const GET_CATEGORY_DETAILS_SUCCESS = 'GET_CATEGORY_DETAILS_SUCCESS'
export const GET_CATEGORY_DETAILS_FAIL = 'GET_CATEGORY_DETAILS_FAIL'