export const CREATE_DONATION_REQUEST = 'CREATE_DONATION_REQUEST'
export const CREATE_DONATION_SUCCESS = 'CREATE_DONATION_SUCCESS'
export const CREATE_DONATION_FAIL = 'CREATE_DONATION_FAIL'
export const CREATE_DONATION_RESET = 'CREATE_DONATION_RESET'